// Dashboard statistics action types

// prettier-ignore
export enum actionsName {
  GET_DASHBOARD_STATISTICS = "GET_DASHBOARD_STATISTICS",
  GET_DASHBOARD_STATISTICS_SUCCESS = "GET_DASHBOARD_STATISTICS_SUCCESS",
  GET_DASHBOARD_STATISTICS_FAILED = "GET_DASHBOARD_STATISTICS_FAILED",
  GET_DASHBOARD_STATISTICS_CLEANUP = "GET_DASHBOARD_STATISTICS_CLEANUP",

  GET_USER_STATISTICS = "GET_USER_STATISTICS",
  GET_USER_STATISTICS_SUCCESS = "GET_USER_STATISTICS_SUCCESS",
  GET_USER_STATISTICS_FAILED = "GET_USER_STATISTICS_FAILED",
  GET_USER_STATISTICS_CLEANUP = "GET_USER_STATISTICS_CLEANUP",

  GET_CAR_STATISTICS = "GET_CAR_STATISTICS",
  GET_CAR_STATISTICS_SUCCESS = "GET_CAR_STATISTICS_SUCCESS",
  GET_CAR_STATISTICS_FAILED = "GET_CAR_STATISTICS_FAILED",
  GET_CAR_STATISTICS_CLEANUP = "GET_CAR_STATISTICS_CLEANUP",

  GET_COMMUNITY_STATISTICS = "GET_COMMUNITY_STATISTICS",
  GET_COMMUNITY_STATISTICS_SUCCESS = "GET_COMMUNITY_STATISTICS_SUCCESS",
  GET_COMMUNITY_STATISTICS_FAILED = "GET_COMMUNITY_STATISTICS_FAILED",
  GET_COMMUNITY_STATISTICS_CLEANUP = "GET_COMMUNITY_STATISTICS_CLEANUP",

  GET_ENGAGEMENT_STATISTICS = "GET_ENGAGEMENT_STATISTICS",
  GET_ENGAGEMENT_STATISTICS_SUCCESS = "GET_ENGAGEMENT_STATISTICS_SUCCESS",
  GET_ENGAGEMENT_STATISTICS_FAILED = "GET_ENGAGEMENT_STATISTICS_FAILED",
  GET_ENGAGEMENT_STATISTICS_CLEANUP = "GET_ENGAGEMENT_STATISTICS_CLEANUP",

  GET_ACTIVITY_CHARTS_STATISTICS = "GET_ACTIVITY_CHARTS_STATISTICS",
  GET_ACTIVITY_CHARTS_STATISTICS_SUCCESS = "GET_ACTIVITY_CHARTS_STATISTICS_SUCCESS",
  GET_ACTIVITY_CHARTS_STATISTICS_FAILED = "GET_ACTIVITY_CHARTS_STATISTICS_FAILED",
  GET_ACTIVITY_CHARTS_STATISTICS_CLEANUP = "GET_ACTIVITY_CHARTS_STATISTICS_CLEANUP",

  //dontRemoveMeNames,
}

export type actionName = typeof actionsName[keyof typeof actionsName]

export type actionType = {
  [K in keyof typeof actionsName]: {
    type: typeof actionsName[K]
    // for now we don't strictly type payloads – keep generic
    payload: any
  }
}[keyof typeof actionsName]

