export enum ShamcarRoutes {
  Dashboard = '/dashboard',
  Login = '/login',
  PROFILE = '/profile',
  Logut = '/logout',
  ERROR = '/error',
  REGISTER = '/REGISTER',
  USERS = '/users',
  ADMINS= '/admins',
  CAR_MODELS = '/car-models',
  CAR_MAKES = '/car-makes',
  REVIEWS = '/reviews',
  QUESTIONS = '/questions',
  CAR_TRIMS = '/car-trims',
  ADD_CAR_TRIM = '/car-trims/add',
  UPDATE_CAR_TRIM = '/car-trims/update/:id',
  STATISTICS = '/statistics',
}
